spring:
  #  profiles:
  #    active: dev
  messages:
    basename: messages, errors
  output:
    ansi:
      enabled: always
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mygg1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    #    jdbc:mysql://localhost:3306/DB_NAME?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1235
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
#        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    session:
      cookie:
        http-only: true
        max-age: 259200
        path: /

logging.level:
  org:
    hibernate.SQL: debug
    springframework:
      security: debug
#  io.lettuce.core: TRACE
#  org.hibernate.orm.jdbc.bind: trace
#      web.cors.DefaultCorsProcessor: trace # cors log

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

api:
  riot:
    api-key: ENC(lq0wT0I/GrcapU+9bVdgb6yK6Y003WsKh5iRCBBGXrYyb/OetxZ6QuBeD2Ao4+5u2pMGUVnJDYY=)
    asia-url: ENC(wKciqLaIhlON2SwIi4TncRf/yZm93SOZWzS2A8nvJljTwuSMQY4m2w==)
    kr-url: ENC(toSmzMYSpbpSX4CK9/edFjswqRkpHYt3U4X//oOFZNExmChzv8jHnA==)
