spring:
  #  profiles:
  #    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mygg1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    jdbc:mysql://localhost:3306/DB_NAME?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1235

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

ddragon:
  path: ENC(5nbh5RlhI66tx04Atb01hhTfKRlPXK2mxblJp524Y9RGrKcerVH4cnaz/h2HKA6ePdLscWJu2iJjxM7ZVXMNVQ==)

api:
  riot:
    api-key: ENC(IGioYZTNUIFqqXqHQtNIvRsI9azyN1auoLKaPpqnZv2P+JTwTDmP7l9rQIbGite55Ys5u05Oz+w=)
    asia-url: ENC(+fu97w0afKR84ez9dtvdMuFjtXMIJGZ1KsZs6NcrPj/BtAq9gDAkWw==)
    kr-url: ENC(Sr12CtptJZ/cs1LQoqFcXCLbtvlrH+Uvcbch3lIxzbjo8TksHlxFLA==)
    data-dragon: ENC(Mwv1iQDyfLbqIgfMTYCXMZq102YnCBjbmRAfJVG2/iOoOw955ez5p6RPZ5LLWtN0)